### ISSUE TITLE
BUG :: Markdown text has to have no spaces before 

### ISSUE THREAD

**Issue by spynetS** [spynetS/RapidElements#26]
If there is spaces before the markdown it will not get parsed

**Comment by SharkooMaster** [comment]
don't add spaces before the text then. Solved

![10-Year-Old-Boy-Starts-Petition-to-Change-Nerd-Glasses-Emoji-112923-bec304032f7a45e2aa4957e003755126](https://github.com/spynetS/RapidElements/assets/44705253/ec46f4dc-5542-46de-a422-bf1c11e404dc)
